include: package:effective_dart/analysis_options.yaml
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "test/**"

linter:
  rules:
    public_member_api_docs: false
    one_member_abstracts: false
    prefer_const_constructors: true